/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TtsTestRouteImport } from './routes/tts-test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewTestRouteImport } from './routes/interview-test'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EmployeeRouteImport } from './routes/_employee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BewerbungIndexRouteImport } from './routes/bewerbung.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TerminTokenRouteImport } from './routes/termin.$token'
import { Route as InterviewAppIdRouteImport } from './routes/interview.$appId'
import { Route as BewerbungVerbindenRouteImport } from './routes/bewerbung.verbinden'
import { Route as AuthConfirmedRouteImport } from './routes/auth.confirmed'
import { Route as AdminVermittlungRouteImport } from './routes/admin.vermittlung'
import { Route as AdminVerfuegbarkeitRouteImport } from './routes/admin.verfuegbarkeit'
import { Route as AdminUploadsRouteImport } from './routes/admin.uploads'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminTeamLeaderSettingsRouteImport } from './routes/admin.team-leader-settings'
import { Route as AdminStatistikenRouteImport } from './routes/admin.statistiken'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevisionsRouteImport } from './routes/admin.revisions'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminRecoveryRouteImport } from './routes/admin.recovery'
import { Route as AdminPostRouteImport } from './routes/admin.post'
import { Route as AdminPersonenRouteImport } from './routes/admin.personen'
import { Route as AdminPartnerCompaniesRouteImport } from './routes/admin.partner-companies'
import { Route as AdminMitarbeiterRouteImport } from './routes/admin.mitarbeiter'
import { Route as AdminLandingGeneratorRouteImport } from './routes/admin.landing-generator'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminInfrastructureRouteImport } from './routes/admin.infrastructure'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminEmailLogsRouteImport } from './routes/admin.email-logs'
import { Route as AdminEmailCenterRouteImport } from './routes/admin.email-center'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminCalendlyRouteImport } from './routes/admin.calendly'
import { Route as AdminBewerbungenRouteImport } from './routes/admin.bewerbungen'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAiSettingsRouteImport } from './routes/admin.ai-settings'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as EmployeeVerificationRouteImport } from './routes/_employee/verification'
import { Route as EmployeeTasksRouteImport } from './routes/_employee/tasks'
import { Route as EmployeeSmsRouteImport } from './routes/_employee/sms'
import { Route as EmployeeSettingsRouteImport } from './routes/_employee/settings'
import { Route as EmployeePersonalDataRouteImport } from './routes/_employee/personal-data'
import { Route as EmployeeOnboardingRouteImport } from './routes/_employee/onboarding'
import { Route as EmployeeNotificationsRouteImport } from './routes/_employee/notifications'
import { Route as EmployeeEarningsRouteImport } from './routes/_employee/earnings'
import { Route as EmployeeDocumentsRouteImport } from './routes/_employee/documents'
import { Route as EmployeeDashboardRouteImport } from './routes/_employee/dashboard'
import { Route as EmployeeContractRouteImport } from './routes/_employee/contract'
import { Route as EmployeeChatRouteImport } from './routes/_employee/chat'
import { Route as EmployeeAppointmentsRouteImport } from './routes/_employee/appointments'
import { Route as AdminTasksIndexRouteImport } from './routes/admin.tasks.index'
import { Route as TerminBuchenTokenRouteImport } from './routes/termin.buchen.$token'
import { Route as InterviewVoiceAppIdRouteImport } from './routes/interview.voice.$appId'
import { Route as ApiPublicTtsTestRouteImport } from './routes/api/public/tts-test'
import { Route as ApiPublicSmsPollCronRouteImport } from './routes/api/public/sms-poll-cron'
import { Route as ApiPublicLandingServerHeartbeatRouteImport } from './routes/api/public/landing-server-heartbeat'
import { Route as ApiPublicLandingServerBootstrapRouteImport } from './routes/api/public/landing-server-bootstrap'
import { Route as ApiPublicInterviewVoiceRouteImport } from './routes/api/public/interview-voice'
import { Route as ApiPublicInterviewTestCreateRouteImport } from './routes/api/public/interview-test-create'
import { Route as ApiPublicInterviewChatRouteImport } from './routes/api/public/interview-chat'
import { Route as ApiPublicDomainHealthCronRouteImport } from './routes/api/public/domain-health-cron'
import { Route as ApiPublicCalendlyWebhookRouteImport } from './routes/api/public/calendly-webhook'
import { Route as ApiPublicApplicationsRouteImport } from './routes/api/public/applications'
import { Route as ApiPublicApplicationLookupRouteImport } from './routes/api/public/application-lookup'
import { Route as ApiPublicApplicationByTokenRouteImport } from './routes/api/public/application-by-token'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai-chat'
import { Route as AdminPersonenIdRouteImport } from './routes/admin.personen.$id'
import { Route as AdminAssignmentsAssignmentIdRouteImport } from './routes/admin.assignments.$assignmentId'
import { Route as EmployeeTasksAssignmentIdRouteImport } from './routes/_employee/tasks.$assignmentId'
import { Route as ApiPublicLandingServerFilesSplatRouteImport } from './routes/api/public/landing-server-files.$'
import { Route as AdminTasksBuilderTemplateIdRouteImport } from './routes/admin.tasks.builder.$templateId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TtsTestRoute = TtsTestRouteImport.update({
  id: '/tts-test',
  path: '/tts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTestRoute = InterviewTestRouteImport.update({
  id: '/interview-test',
  path: '/interview-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/_employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BewerbungIndexRoute = BewerbungIndexRouteImport.update({
  id: '/bewerbung/',
  path: '/bewerbung/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TerminTokenRoute = TerminTokenRouteImport.update({
  id: '/termin/$token',
  path: '/termin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewAppIdRoute = InterviewAppIdRouteImport.update({
  id: '/interview/$appId',
  path: '/interview/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const BewerbungVerbindenRoute = BewerbungVerbindenRouteImport.update({
  id: '/bewerbung/verbinden',
  path: '/bewerbung/verbinden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVermittlungRoute = AdminVermittlungRouteImport.update({
  id: '/vermittlung',
  path: '/vermittlung',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerfuegbarkeitRoute = AdminVerfuegbarkeitRouteImport.update({
  id: '/verfuegbarkeit',
  path: '/verfuegbarkeit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamLeaderSettingsRoute = AdminTeamLeaderSettingsRouteImport.update({
  id: '/team-leader-settings',
  path: '/team-leader-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatistikenRoute = AdminStatistikenRouteImport.update({
  id: '/statistiken',
  path: '/statistiken',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevisionsRoute = AdminRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoveryRoute = AdminRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostRoute = AdminPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonenRoute = AdminPersonenRouteImport.update({
  id: '/personen',
  path: '/personen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnerCompaniesRoute = AdminPartnerCompaniesRouteImport.update({
  id: '/partner-companies',
  path: '/partner-companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMitarbeiterRoute = AdminMitarbeiterRouteImport.update({
  id: '/mitarbeiter',
  path: '/mitarbeiter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingGeneratorRoute = AdminLandingGeneratorRouteImport.update({
  id: '/landing-generator',
  path: '/landing-generator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailLogsRoute = AdminEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailCenterRoute = AdminEmailCenterRouteImport.update({
  id: '/email-center',
  path: '/email-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendlyRoute = AdminCalendlyRouteImport.update({
  id: '/calendly',
  path: '/calendly',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBewerbungenRoute = AdminBewerbungenRouteImport.update({
  id: '/bewerbungen',
  path: '/bewerbungen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeVerificationRoute = EmployeeVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSmsRoute = EmployeeSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePersonalDataRoute = EmployeePersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOnboardingRoute = EmployeeOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeEarningsRoute = EmployeeEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDocumentsRoute = EmployeeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeContractRoute = EmployeeContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeChatRoute = EmployeeChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAppointmentsRoute = EmployeeAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const TerminBuchenTokenRoute = TerminBuchenTokenRouteImport.update({
  id: '/termin/buchen/$token',
  path: '/termin/buchen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewVoiceAppIdRoute = InterviewVoiceAppIdRouteImport.update({
  id: '/interview/voice/$appId',
  path: '/interview/voice/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsTestRoute = ApiPublicTtsTestRouteImport.update({
  id: '/api/public/tts-test',
  path: '/api/public/tts-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsPollCronRoute = ApiPublicSmsPollCronRouteImport.update({
  id: '/api/public/sms-poll-cron',
  path: '/api/public/sms-poll-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingServerHeartbeatRoute =
  ApiPublicLandingServerHeartbeatRouteImport.update({
    id: '/api/public/landing-server-heartbeat',
    path: '/api/public/landing-server-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLandingServerBootstrapRoute =
  ApiPublicLandingServerBootstrapRouteImport.update({
    id: '/api/public/landing-server-bootstrap',
    path: '/api/public/landing-server-bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInterviewVoiceRoute = ApiPublicInterviewVoiceRouteImport.update({
  id: '/api/public/interview-voice',
  path: '/api/public/interview-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInterviewTestCreateRoute =
  ApiPublicInterviewTestCreateRouteImport.update({
    id: '/api/public/interview-test-create',
    path: '/api/public/interview-test-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInterviewChatRoute = ApiPublicInterviewChatRouteImport.update({
  id: '/api/public/interview-chat',
  path: '/api/public/interview-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDomainHealthCronRoute =
  ApiPublicDomainHealthCronRouteImport.update({
    id: '/api/public/domain-health-cron',
    path: '/api/public/domain-health-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendlyWebhookRoute =
  ApiPublicCalendlyWebhookRouteImport.update({
    id: '/api/public/calendly-webhook',
    path: '/api/public/calendly-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApplicationsRoute = ApiPublicApplicationsRouteImport.update({
  id: '/api/public/applications',
  path: '/api/public/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplicationLookupRoute =
  ApiPublicApplicationLookupRouteImport.update({
    id: '/api/public/application-lookup',
    path: '/api/public/application-lookup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApplicationByTokenRoute =
  ApiPublicApplicationByTokenRouteImport.update({
    id: '/api/public/application-by-token',
    path: '/api/public/application-by-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai-chat',
  path: '/api/public/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPersonenIdRoute = AdminPersonenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPersonenRoute,
} as any)
const AdminAssignmentsAssignmentIdRoute =
  AdminAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const EmployeeTasksAssignmentIdRoute =
  EmployeeTasksAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => EmployeeTasksRoute,
  } as any)
const ApiPublicLandingServerFilesSplatRoute =
  ApiPublicLandingServerFilesSplatRouteImport.update({
    id: '/api/public/landing-server-files/$',
    path: '/api/public/landing-server-files/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTasksBuilderTemplateIdRoute =
  AdminTasksBuilderTemplateIdRouteImport.update({
    id: '/tasks/builder/$templateId',
    path: '/tasks/builder/$templateId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-test': typeof InterviewTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tts-test': typeof TtsTestRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/appointments': typeof EmployeeAppointmentsRoute
  '/chat': typeof EmployeeChatRoute
  '/contract': typeof EmployeeContractRoute
  '/dashboard': typeof EmployeeDashboardRoute
  '/documents': typeof EmployeeDocumentsRoute
  '/earnings': typeof EmployeeEarningsRoute
  '/notifications': typeof EmployeeNotificationsRoute
  '/onboarding': typeof EmployeeOnboardingRoute
  '/personal-data': typeof EmployeePersonalDataRoute
  '/settings': typeof EmployeeSettingsRoute
  '/sms': typeof EmployeeSmsRoute
  '/tasks': typeof EmployeeTasksRouteWithChildren
  '/verification': typeof EmployeeVerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bewerbungen': typeof AdminBewerbungenRoute
  '/admin/calendly': typeof AdminCalendlyRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-center': typeof AdminEmailCenterRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-generator': typeof AdminLandingGeneratorRoute
  '/admin/mitarbeiter': typeof AdminMitarbeiterRoute
  '/admin/partner-companies': typeof AdminPartnerCompaniesRoute
  '/admin/personen': typeof AdminPersonenRouteWithChildren
  '/admin/post': typeof AdminPostRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/statistiken': typeof AdminStatistikenRoute
  '/admin/team-leader-settings': typeof AdminTeamLeaderSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/verfuegbarkeit': typeof AdminVerfuegbarkeitRoute
  '/admin/vermittlung': typeof AdminVermittlungRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/bewerbung/verbinden': typeof BewerbungVerbindenRoute
  '/interview/$appId': typeof InterviewAppIdRoute
  '/termin/$token': typeof TerminTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/bewerbung/': typeof BewerbungIndexRoute
  '/tasks/$assignmentId': typeof EmployeeTasksAssignmentIdRoute
  '/admin/assignments/$assignmentId': typeof AdminAssignmentsAssignmentIdRoute
  '/admin/personen/$id': typeof AdminPersonenIdRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/application-by-token': typeof ApiPublicApplicationByTokenRoute
  '/api/public/application-lookup': typeof ApiPublicApplicationLookupRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/domain-health-cron': typeof ApiPublicDomainHealthCronRoute
  '/api/public/interview-chat': typeof ApiPublicInterviewChatRoute
  '/api/public/interview-test-create': typeof ApiPublicInterviewTestCreateRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/landing-server-bootstrap': typeof ApiPublicLandingServerBootstrapRoute
  '/api/public/landing-server-heartbeat': typeof ApiPublicLandingServerHeartbeatRoute
  '/api/public/sms-poll-cron': typeof ApiPublicSmsPollCronRoute
  '/api/public/tts-test': typeof ApiPublicTtsTestRoute
  '/interview/voice/$appId': typeof InterviewVoiceAppIdRoute
  '/termin/buchen/$token': typeof TerminBuchenTokenRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/tasks/builder/$templateId': typeof AdminTasksBuilderTemplateIdRoute
  '/api/public/landing-server-files/$': typeof ApiPublicLandingServerFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-test': typeof InterviewTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tts-test': typeof TtsTestRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/appointments': typeof EmployeeAppointmentsRoute
  '/chat': typeof EmployeeChatRoute
  '/contract': typeof EmployeeContractRoute
  '/dashboard': typeof EmployeeDashboardRoute
  '/documents': typeof EmployeeDocumentsRoute
  '/earnings': typeof EmployeeEarningsRoute
  '/notifications': typeof EmployeeNotificationsRoute
  '/onboarding': typeof EmployeeOnboardingRoute
  '/personal-data': typeof EmployeePersonalDataRoute
  '/settings': typeof EmployeeSettingsRoute
  '/sms': typeof EmployeeSmsRoute
  '/tasks': typeof EmployeeTasksRouteWithChildren
  '/verification': typeof EmployeeVerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bewerbungen': typeof AdminBewerbungenRoute
  '/admin/calendly': typeof AdminCalendlyRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-center': typeof AdminEmailCenterRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-generator': typeof AdminLandingGeneratorRoute
  '/admin/mitarbeiter': typeof AdminMitarbeiterRoute
  '/admin/partner-companies': typeof AdminPartnerCompaniesRoute
  '/admin/personen': typeof AdminPersonenRouteWithChildren
  '/admin/post': typeof AdminPostRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/statistiken': typeof AdminStatistikenRoute
  '/admin/team-leader-settings': typeof AdminTeamLeaderSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/verfuegbarkeit': typeof AdminVerfuegbarkeitRoute
  '/admin/vermittlung': typeof AdminVermittlungRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/bewerbung/verbinden': typeof BewerbungVerbindenRoute
  '/interview/$appId': typeof InterviewAppIdRoute
  '/termin/$token': typeof TerminTokenRoute
  '/admin': typeof AdminIndexRoute
  '/bewerbung': typeof BewerbungIndexRoute
  '/tasks/$assignmentId': typeof EmployeeTasksAssignmentIdRoute
  '/admin/assignments/$assignmentId': typeof AdminAssignmentsAssignmentIdRoute
  '/admin/personen/$id': typeof AdminPersonenIdRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/application-by-token': typeof ApiPublicApplicationByTokenRoute
  '/api/public/application-lookup': typeof ApiPublicApplicationLookupRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/domain-health-cron': typeof ApiPublicDomainHealthCronRoute
  '/api/public/interview-chat': typeof ApiPublicInterviewChatRoute
  '/api/public/interview-test-create': typeof ApiPublicInterviewTestCreateRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/landing-server-bootstrap': typeof ApiPublicLandingServerBootstrapRoute
  '/api/public/landing-server-heartbeat': typeof ApiPublicLandingServerHeartbeatRoute
  '/api/public/sms-poll-cron': typeof ApiPublicSmsPollCronRoute
  '/api/public/tts-test': typeof ApiPublicTtsTestRoute
  '/interview/voice/$appId': typeof InterviewVoiceAppIdRoute
  '/termin/buchen/$token': typeof TerminBuchenTokenRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/tasks/builder/$templateId': typeof AdminTasksBuilderTemplateIdRoute
  '/api/public/landing-server-files/$': typeof ApiPublicLandingServerFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_employee': typeof EmployeeRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-test': typeof InterviewTestRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tts-test': typeof TtsTestRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_employee/appointments': typeof EmployeeAppointmentsRoute
  '/_employee/chat': typeof EmployeeChatRoute
  '/_employee/contract': typeof EmployeeContractRoute
  '/_employee/dashboard': typeof EmployeeDashboardRoute
  '/_employee/documents': typeof EmployeeDocumentsRoute
  '/_employee/earnings': typeof EmployeeEarningsRoute
  '/_employee/notifications': typeof EmployeeNotificationsRoute
  '/_employee/onboarding': typeof EmployeeOnboardingRoute
  '/_employee/personal-data': typeof EmployeePersonalDataRoute
  '/_employee/settings': typeof EmployeeSettingsRoute
  '/_employee/sms': typeof EmployeeSmsRoute
  '/_employee/tasks': typeof EmployeeTasksRouteWithChildren
  '/_employee/verification': typeof EmployeeVerificationRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bewerbungen': typeof AdminBewerbungenRoute
  '/admin/calendly': typeof AdminCalendlyRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/email-center': typeof AdminEmailCenterRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-generator': typeof AdminLandingGeneratorRoute
  '/admin/mitarbeiter': typeof AdminMitarbeiterRoute
  '/admin/partner-companies': typeof AdminPartnerCompaniesRoute
  '/admin/personen': typeof AdminPersonenRouteWithChildren
  '/admin/post': typeof AdminPostRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/statistiken': typeof AdminStatistikenRoute
  '/admin/team-leader-settings': typeof AdminTeamLeaderSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/verfuegbarkeit': typeof AdminVerfuegbarkeitRoute
  '/admin/vermittlung': typeof AdminVermittlungRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/bewerbung/verbinden': typeof BewerbungVerbindenRoute
  '/interview/$appId': typeof InterviewAppIdRoute
  '/termin/$token': typeof TerminTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/bewerbung/': typeof BewerbungIndexRoute
  '/_employee/tasks/$assignmentId': typeof EmployeeTasksAssignmentIdRoute
  '/admin/assignments/$assignmentId': typeof AdminAssignmentsAssignmentIdRoute
  '/admin/personen/$id': typeof AdminPersonenIdRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/application-by-token': typeof ApiPublicApplicationByTokenRoute
  '/api/public/application-lookup': typeof ApiPublicApplicationLookupRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/domain-health-cron': typeof ApiPublicDomainHealthCronRoute
  '/api/public/interview-chat': typeof ApiPublicInterviewChatRoute
  '/api/public/interview-test-create': typeof ApiPublicInterviewTestCreateRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/landing-server-bootstrap': typeof ApiPublicLandingServerBootstrapRoute
  '/api/public/landing-server-heartbeat': typeof ApiPublicLandingServerHeartbeatRoute
  '/api/public/sms-poll-cron': typeof ApiPublicSmsPollCronRoute
  '/api/public/tts-test': typeof ApiPublicTtsTestRoute
  '/interview/voice/$appId': typeof InterviewVoiceAppIdRoute
  '/termin/buchen/$token': typeof TerminBuchenTokenRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/tasks/builder/$templateId': typeof AdminTasksBuilderTemplateIdRoute
  '/api/public/landing-server-files/$': typeof ApiPublicLandingServerFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/interview-test'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/tts-test'
    | '/unsubscribe'
    | '/appointments'
    | '/chat'
    | '/contract'
    | '/dashboard'
    | '/documents'
    | '/earnings'
    | '/notifications'
    | '/onboarding'
    | '/personal-data'
    | '/settings'
    | '/sms'
    | '/tasks'
    | '/verification'
    | '/admin/activity'
    | '/admin/ai-settings'
    | '/admin/appointments'
    | '/admin/bewerbungen'
    | '/admin/calendly'
    | '/admin/chat'
    | '/admin/contracts'
    | '/admin/domains'
    | '/admin/email-center'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/infrastructure'
    | '/admin/kyc'
    | '/admin/landing-generator'
    | '/admin/mitarbeiter'
    | '/admin/partner-companies'
    | '/admin/personen'
    | '/admin/post'
    | '/admin/recovery'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/revisions'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/statistiken'
    | '/admin/team-leader-settings'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/admin/uploads'
    | '/admin/verfuegbarkeit'
    | '/admin/vermittlung'
    | '/auth/confirmed'
    | '/bewerbung/verbinden'
    | '/interview/$appId'
    | '/termin/$token'
    | '/admin/'
    | '/bewerbung/'
    | '/tasks/$assignmentId'
    | '/admin/assignments/$assignmentId'
    | '/admin/personen/$id'
    | '/api/public/ai-chat'
    | '/api/public/application-by-token'
    | '/api/public/application-lookup'
    | '/api/public/applications'
    | '/api/public/calendly-webhook'
    | '/api/public/domain-health-cron'
    | '/api/public/interview-chat'
    | '/api/public/interview-test-create'
    | '/api/public/interview-voice'
    | '/api/public/landing-server-bootstrap'
    | '/api/public/landing-server-heartbeat'
    | '/api/public/sms-poll-cron'
    | '/api/public/tts-test'
    | '/interview/voice/$appId'
    | '/termin/buchen/$token'
    | '/admin/tasks/'
    | '/admin/tasks/builder/$templateId'
    | '/api/public/landing-server-files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/interview-test'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/tts-test'
    | '/unsubscribe'
    | '/appointments'
    | '/chat'
    | '/contract'
    | '/dashboard'
    | '/documents'
    | '/earnings'
    | '/notifications'
    | '/onboarding'
    | '/personal-data'
    | '/settings'
    | '/sms'
    | '/tasks'
    | '/verification'
    | '/admin/activity'
    | '/admin/ai-settings'
    | '/admin/appointments'
    | '/admin/bewerbungen'
    | '/admin/calendly'
    | '/admin/chat'
    | '/admin/contracts'
    | '/admin/domains'
    | '/admin/email-center'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/infrastructure'
    | '/admin/kyc'
    | '/admin/landing-generator'
    | '/admin/mitarbeiter'
    | '/admin/partner-companies'
    | '/admin/personen'
    | '/admin/post'
    | '/admin/recovery'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/revisions'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/statistiken'
    | '/admin/team-leader-settings'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/admin/uploads'
    | '/admin/verfuegbarkeit'
    | '/admin/vermittlung'
    | '/auth/confirmed'
    | '/bewerbung/verbinden'
    | '/interview/$appId'
    | '/termin/$token'
    | '/admin'
    | '/bewerbung'
    | '/tasks/$assignmentId'
    | '/admin/assignments/$assignmentId'
    | '/admin/personen/$id'
    | '/api/public/ai-chat'
    | '/api/public/application-by-token'
    | '/api/public/application-lookup'
    | '/api/public/applications'
    | '/api/public/calendly-webhook'
    | '/api/public/domain-health-cron'
    | '/api/public/interview-chat'
    | '/api/public/interview-test-create'
    | '/api/public/interview-voice'
    | '/api/public/landing-server-bootstrap'
    | '/api/public/landing-server-heartbeat'
    | '/api/public/sms-poll-cron'
    | '/api/public/tts-test'
    | '/interview/voice/$appId'
    | '/termin/buchen/$token'
    | '/admin/tasks'
    | '/admin/tasks/builder/$templateId'
    | '/api/public/landing-server-files/$'
  id:
    | '__root__'
    | '/'
    | '/_employee'
    | '/admin'
    | '/forgot-password'
    | '/interview-test'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/tts-test'
    | '/unsubscribe'
    | '/_employee/appointments'
    | '/_employee/chat'
    | '/_employee/contract'
    | '/_employee/dashboard'
    | '/_employee/documents'
    | '/_employee/earnings'
    | '/_employee/notifications'
    | '/_employee/onboarding'
    | '/_employee/personal-data'
    | '/_employee/settings'
    | '/_employee/sms'
    | '/_employee/tasks'
    | '/_employee/verification'
    | '/admin/activity'
    | '/admin/ai-settings'
    | '/admin/appointments'
    | '/admin/bewerbungen'
    | '/admin/calendly'
    | '/admin/chat'
    | '/admin/contracts'
    | '/admin/domains'
    | '/admin/email-center'
    | '/admin/email-logs'
    | '/admin/email-templates'
    | '/admin/infrastructure'
    | '/admin/kyc'
    | '/admin/landing-generator'
    | '/admin/mitarbeiter'
    | '/admin/partner-companies'
    | '/admin/personen'
    | '/admin/post'
    | '/admin/recovery'
    | '/admin/reminders'
    | '/admin/reviews'
    | '/admin/revisions'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/statistiken'
    | '/admin/team-leader-settings'
    | '/admin/tenants'
    | '/admin/transactions'
    | '/admin/uploads'
    | '/admin/verfuegbarkeit'
    | '/admin/vermittlung'
    | '/auth/confirmed'
    | '/bewerbung/verbinden'
    | '/interview/$appId'
    | '/termin/$token'
    | '/admin/'
    | '/bewerbung/'
    | '/_employee/tasks/$assignmentId'
    | '/admin/assignments/$assignmentId'
    | '/admin/personen/$id'
    | '/api/public/ai-chat'
    | '/api/public/application-by-token'
    | '/api/public/application-lookup'
    | '/api/public/applications'
    | '/api/public/calendly-webhook'
    | '/api/public/domain-health-cron'
    | '/api/public/interview-chat'
    | '/api/public/interview-test-create'
    | '/api/public/interview-voice'
    | '/api/public/landing-server-bootstrap'
    | '/api/public/landing-server-heartbeat'
    | '/api/public/sms-poll-cron'
    | '/api/public/tts-test'
    | '/interview/voice/$appId'
    | '/termin/buchen/$token'
    | '/admin/tasks/'
    | '/admin/tasks/builder/$templateId'
    | '/api/public/landing-server-files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterviewTestRoute: typeof InterviewTestRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TtsTestRoute: typeof TtsTestRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  BewerbungVerbindenRoute: typeof BewerbungVerbindenRoute
  InterviewAppIdRoute: typeof InterviewAppIdRoute
  TerminTokenRoute: typeof TerminTokenRoute
  BewerbungIndexRoute: typeof BewerbungIndexRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicApplicationByTokenRoute: typeof ApiPublicApplicationByTokenRoute
  ApiPublicApplicationLookupRoute: typeof ApiPublicApplicationLookupRoute
  ApiPublicApplicationsRoute: typeof ApiPublicApplicationsRoute
  ApiPublicCalendlyWebhookRoute: typeof ApiPublicCalendlyWebhookRoute
  ApiPublicDomainHealthCronRoute: typeof ApiPublicDomainHealthCronRoute
  ApiPublicInterviewChatRoute: typeof ApiPublicInterviewChatRoute
  ApiPublicInterviewTestCreateRoute: typeof ApiPublicInterviewTestCreateRoute
  ApiPublicInterviewVoiceRoute: typeof ApiPublicInterviewVoiceRoute
  ApiPublicLandingServerBootstrapRoute: typeof ApiPublicLandingServerBootstrapRoute
  ApiPublicLandingServerHeartbeatRoute: typeof ApiPublicLandingServerHeartbeatRoute
  ApiPublicSmsPollCronRoute: typeof ApiPublicSmsPollCronRoute
  ApiPublicTtsTestRoute: typeof ApiPublicTtsTestRoute
  InterviewVoiceAppIdRoute: typeof InterviewVoiceAppIdRoute
  TerminBuchenTokenRoute: typeof TerminBuchenTokenRoute
  ApiPublicLandingServerFilesSplatRoute: typeof ApiPublicLandingServerFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tts-test': {
      id: '/tts-test'
      path: '/tts-test'
      fullPath: '/tts-test'
      preLoaderRoute: typeof TtsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-test': {
      id: '/interview-test'
      path: '/interview-test'
      fullPath: '/interview-test'
      preLoaderRoute: typeof InterviewTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee': {
      id: '/_employee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerbung/': {
      id: '/bewerbung/'
      path: '/bewerbung'
      fullPath: '/bewerbung/'
      preLoaderRoute: typeof BewerbungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/termin/$token': {
      id: '/termin/$token'
      path: '/termin/$token'
      fullPath: '/termin/$token'
      preLoaderRoute: typeof TerminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$appId': {
      id: '/interview/$appId'
      path: '/interview/$appId'
      fullPath: '/interview/$appId'
      preLoaderRoute: typeof InterviewAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerbung/verbinden': {
      id: '/bewerbung/verbinden'
      path: '/bewerbung/verbinden'
      fullPath: '/bewerbung/verbinden'
      preLoaderRoute: typeof BewerbungVerbindenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmed': {
      id: '/auth/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vermittlung': {
      id: '/admin/vermittlung'
      path: '/vermittlung'
      fullPath: '/admin/vermittlung'
      preLoaderRoute: typeof AdminVermittlungRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verfuegbarkeit': {
      id: '/admin/verfuegbarkeit'
      path: '/verfuegbarkeit'
      fullPath: '/admin/verfuegbarkeit'
      preLoaderRoute: typeof AdminVerfuegbarkeitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team-leader-settings': {
      id: '/admin/team-leader-settings'
      path: '/team-leader-settings'
      fullPath: '/admin/team-leader-settings'
      preLoaderRoute: typeof AdminTeamLeaderSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statistiken': {
      id: '/admin/statistiken'
      path: '/statistiken'
      fullPath: '/admin/statistiken'
      preLoaderRoute: typeof AdminStatistikenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revisions': {
      id: '/admin/revisions'
      path: '/revisions'
      fullPath: '/admin/revisions'
      preLoaderRoute: typeof AdminRevisionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recovery': {
      id: '/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AdminRecoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/post': {
      id: '/admin/post'
      path: '/post'
      fullPath: '/admin/post'
      preLoaderRoute: typeof AdminPostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personen': {
      id: '/admin/personen'
      path: '/personen'
      fullPath: '/admin/personen'
      preLoaderRoute: typeof AdminPersonenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partner-companies': {
      id: '/admin/partner-companies'
      path: '/partner-companies'
      fullPath: '/admin/partner-companies'
      preLoaderRoute: typeof AdminPartnerCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mitarbeiter': {
      id: '/admin/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/admin/mitarbeiter'
      preLoaderRoute: typeof AdminMitarbeiterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-generator': {
      id: '/admin/landing-generator'
      path: '/landing-generator'
      fullPath: '/admin/landing-generator'
      preLoaderRoute: typeof AdminLandingGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-logs': {
      id: '/admin/email-logs'
      path: '/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AdminEmailLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-center': {
      id: '/admin/email-center'
      path: '/email-center'
      fullPath: '/admin/email-center'
      preLoaderRoute: typeof AdminEmailCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendly': {
      id: '/admin/calendly'
      path: '/calendly'
      fullPath: '/admin/calendly'
      preLoaderRoute: typeof AdminCalendlyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bewerbungen': {
      id: '/admin/bewerbungen'
      path: '/bewerbungen'
      fullPath: '/admin/bewerbungen'
      preLoaderRoute: typeof AdminBewerbungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_employee/verification': {
      id: '/_employee/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof EmployeeVerificationRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/tasks': {
      id: '/_employee/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/sms': {
      id: '/_employee/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof EmployeeSmsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/settings': {
      id: '/_employee/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/personal-data': {
      id: '/_employee/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof EmployeePersonalDataRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/onboarding': {
      id: '/_employee/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof EmployeeOnboardingRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/notifications': {
      id: '/_employee/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/earnings': {
      id: '/_employee/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EmployeeEarningsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/documents': {
      id: '/_employee/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof EmployeeDocumentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/dashboard': {
      id: '/_employee/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/contract': {
      id: '/_employee/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof EmployeeContractRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/chat': {
      id: '/_employee/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof EmployeeChatRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/appointments': {
      id: '/_employee/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof EmployeeAppointmentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/termin/buchen/$token': {
      id: '/termin/buchen/$token'
      path: '/termin/buchen/$token'
      fullPath: '/termin/buchen/$token'
      preLoaderRoute: typeof TerminBuchenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/voice/$appId': {
      id: '/interview/voice/$appId'
      path: '/interview/voice/$appId'
      fullPath: '/interview/voice/$appId'
      preLoaderRoute: typeof InterviewVoiceAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts-test': {
      id: '/api/public/tts-test'
      path: '/api/public/tts-test'
      fullPath: '/api/public/tts-test'
      preLoaderRoute: typeof ApiPublicTtsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-poll-cron': {
      id: '/api/public/sms-poll-cron'
      path: '/api/public/sms-poll-cron'
      fullPath: '/api/public/sms-poll-cron'
      preLoaderRoute: typeof ApiPublicSmsPollCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-server-heartbeat': {
      id: '/api/public/landing-server-heartbeat'
      path: '/api/public/landing-server-heartbeat'
      fullPath: '/api/public/landing-server-heartbeat'
      preLoaderRoute: typeof ApiPublicLandingServerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing-server-bootstrap': {
      id: '/api/public/landing-server-bootstrap'
      path: '/api/public/landing-server-bootstrap'
      fullPath: '/api/public/landing-server-bootstrap'
      preLoaderRoute: typeof ApiPublicLandingServerBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-voice': {
      id: '/api/public/interview-voice'
      path: '/api/public/interview-voice'
      fullPath: '/api/public/interview-voice'
      preLoaderRoute: typeof ApiPublicInterviewVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-test-create': {
      id: '/api/public/interview-test-create'
      path: '/api/public/interview-test-create'
      fullPath: '/api/public/interview-test-create'
      preLoaderRoute: typeof ApiPublicInterviewTestCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-chat': {
      id: '/api/public/interview-chat'
      path: '/api/public/interview-chat'
      fullPath: '/api/public/interview-chat'
      preLoaderRoute: typeof ApiPublicInterviewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/domain-health-cron': {
      id: '/api/public/domain-health-cron'
      path: '/api/public/domain-health-cron'
      fullPath: '/api/public/domain-health-cron'
      preLoaderRoute: typeof ApiPublicDomainHealthCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendly-webhook': {
      id: '/api/public/calendly-webhook'
      path: '/api/public/calendly-webhook'
      fullPath: '/api/public/calendly-webhook'
      preLoaderRoute: typeof ApiPublicCalendlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/applications': {
      id: '/api/public/applications'
      path: '/api/public/applications'
      fullPath: '/api/public/applications'
      preLoaderRoute: typeof ApiPublicApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/application-lookup': {
      id: '/api/public/application-lookup'
      path: '/api/public/application-lookup'
      fullPath: '/api/public/application-lookup'
      preLoaderRoute: typeof ApiPublicApplicationLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/application-by-token': {
      id: '/api/public/application-by-token'
      path: '/api/public/application-by-token'
      fullPath: '/api/public/application-by-token'
      preLoaderRoute: typeof ApiPublicApplicationByTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-chat': {
      id: '/api/public/ai-chat'
      path: '/api/public/ai-chat'
      fullPath: '/api/public/ai-chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/personen/$id': {
      id: '/admin/personen/$id'
      path: '/$id'
      fullPath: '/admin/personen/$id'
      preLoaderRoute: typeof AdminPersonenIdRouteImport
      parentRoute: typeof AdminPersonenRoute
    }
    '/admin/assignments/$assignmentId': {
      id: '/admin/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/admin/assignments/$assignmentId'
      preLoaderRoute: typeof AdminAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_employee/tasks/$assignmentId': {
      id: '/_employee/tasks/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/tasks/$assignmentId'
      preLoaderRoute: typeof EmployeeTasksAssignmentIdRouteImport
      parentRoute: typeof EmployeeTasksRoute
    }
    '/api/public/landing-server-files/$': {
      id: '/api/public/landing-server-files/$'
      path: '/api/public/landing-server-files/$'
      fullPath: '/api/public/landing-server-files/$'
      preLoaderRoute: typeof ApiPublicLandingServerFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/builder/$templateId': {
      id: '/admin/tasks/builder/$templateId'
      path: '/tasks/builder/$templateId'
      fullPath: '/admin/tasks/builder/$templateId'
      preLoaderRoute: typeof AdminTasksBuilderTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface EmployeeTasksRouteChildren {
  EmployeeTasksAssignmentIdRoute: typeof EmployeeTasksAssignmentIdRoute
}

const EmployeeTasksRouteChildren: EmployeeTasksRouteChildren = {
  EmployeeTasksAssignmentIdRoute: EmployeeTasksAssignmentIdRoute,
}

const EmployeeTasksRouteWithChildren = EmployeeTasksRoute._addFileChildren(
  EmployeeTasksRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeAppointmentsRoute: typeof EmployeeAppointmentsRoute
  EmployeeChatRoute: typeof EmployeeChatRoute
  EmployeeContractRoute: typeof EmployeeContractRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeDocumentsRoute: typeof EmployeeDocumentsRoute
  EmployeeEarningsRoute: typeof EmployeeEarningsRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeOnboardingRoute: typeof EmployeeOnboardingRoute
  EmployeePersonalDataRoute: typeof EmployeePersonalDataRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeSmsRoute: typeof EmployeeSmsRoute
  EmployeeTasksRoute: typeof EmployeeTasksRouteWithChildren
  EmployeeVerificationRoute: typeof EmployeeVerificationRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAppointmentsRoute: EmployeeAppointmentsRoute,
  EmployeeChatRoute: EmployeeChatRoute,
  EmployeeContractRoute: EmployeeContractRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeDocumentsRoute: EmployeeDocumentsRoute,
  EmployeeEarningsRoute: EmployeeEarningsRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeOnboardingRoute: EmployeeOnboardingRoute,
  EmployeePersonalDataRoute: EmployeePersonalDataRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeSmsRoute: EmployeeSmsRoute,
  EmployeeTasksRoute: EmployeeTasksRouteWithChildren,
  EmployeeVerificationRoute: EmployeeVerificationRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface AdminPersonenRouteChildren {
  AdminPersonenIdRoute: typeof AdminPersonenIdRoute
}

const AdminPersonenRouteChildren: AdminPersonenRouteChildren = {
  AdminPersonenIdRoute: AdminPersonenIdRoute,
}

const AdminPersonenRouteWithChildren = AdminPersonenRoute._addFileChildren(
  AdminPersonenRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBewerbungenRoute: typeof AdminBewerbungenRoute
  AdminCalendlyRoute: typeof AdminCalendlyRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminEmailCenterRoute: typeof AdminEmailCenterRoute
  AdminEmailLogsRoute: typeof AdminEmailLogsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLandingGeneratorRoute: typeof AdminLandingGeneratorRoute
  AdminMitarbeiterRoute: typeof AdminMitarbeiterRoute
  AdminPartnerCompaniesRoute: typeof AdminPartnerCompaniesRoute
  AdminPersonenRoute: typeof AdminPersonenRouteWithChildren
  AdminPostRoute: typeof AdminPostRoute
  AdminRecoveryRoute: typeof AdminRecoveryRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRevisionsRoute: typeof AdminRevisionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminStatistikenRoute: typeof AdminStatistikenRoute
  AdminTeamLeaderSettingsRoute: typeof AdminTeamLeaderSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUploadsRoute: typeof AdminUploadsRoute
  AdminVerfuegbarkeitRoute: typeof AdminVerfuegbarkeitRoute
  AdminVermittlungRoute: typeof AdminVermittlungRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssignmentsAssignmentIdRoute: typeof AdminAssignmentsAssignmentIdRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminTasksBuilderTemplateIdRoute: typeof AdminTasksBuilderTemplateIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAiSettingsRoute: AdminAiSettingsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBewerbungenRoute: AdminBewerbungenRoute,
  AdminCalendlyRoute: AdminCalendlyRoute,
  AdminChatRoute: AdminChatRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminEmailCenterRoute: AdminEmailCenterRoute,
  AdminEmailLogsRoute: AdminEmailLogsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLandingGeneratorRoute: AdminLandingGeneratorRoute,
  AdminMitarbeiterRoute: AdminMitarbeiterRoute,
  AdminPartnerCompaniesRoute: AdminPartnerCompaniesRoute,
  AdminPersonenRoute: AdminPersonenRouteWithChildren,
  AdminPostRoute: AdminPostRoute,
  AdminRecoveryRoute: AdminRecoveryRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRevisionsRoute: AdminRevisionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminStatistikenRoute: AdminStatistikenRoute,
  AdminTeamLeaderSettingsRoute: AdminTeamLeaderSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUploadsRoute: AdminUploadsRoute,
  AdminVerfuegbarkeitRoute: AdminVerfuegbarkeitRoute,
  AdminVermittlungRoute: AdminVermittlungRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssignmentsAssignmentIdRoute: AdminAssignmentsAssignmentIdRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminTasksBuilderTemplateIdRoute: AdminTasksBuilderTemplateIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterviewTestRoute: InterviewTestRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TtsTestRoute: TtsTestRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  BewerbungVerbindenRoute: BewerbungVerbindenRoute,
  InterviewAppIdRoute: InterviewAppIdRoute,
  TerminTokenRoute: TerminTokenRoute,
  BewerbungIndexRoute: BewerbungIndexRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicApplicationByTokenRoute: ApiPublicApplicationByTokenRoute,
  ApiPublicApplicationLookupRoute: ApiPublicApplicationLookupRoute,
  ApiPublicApplicationsRoute: ApiPublicApplicationsRoute,
  ApiPublicCalendlyWebhookRoute: ApiPublicCalendlyWebhookRoute,
  ApiPublicDomainHealthCronRoute: ApiPublicDomainHealthCronRoute,
  ApiPublicInterviewChatRoute: ApiPublicInterviewChatRoute,
  ApiPublicInterviewTestCreateRoute: ApiPublicInterviewTestCreateRoute,
  ApiPublicInterviewVoiceRoute: ApiPublicInterviewVoiceRoute,
  ApiPublicLandingServerBootstrapRoute: ApiPublicLandingServerBootstrapRoute,
  ApiPublicLandingServerHeartbeatRoute: ApiPublicLandingServerHeartbeatRoute,
  ApiPublicSmsPollCronRoute: ApiPublicSmsPollCronRoute,
  ApiPublicTtsTestRoute: ApiPublicTtsTestRoute,
  InterviewVoiceAppIdRoute: InterviewVoiceAppIdRoute,
  TerminBuchenTokenRoute: TerminBuchenTokenRoute,
  ApiPublicLandingServerFilesSplatRoute: ApiPublicLandingServerFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
